### ISSUE TITLE
Add `csharpier` as an external formatter

### ISSUE THREAD

**Issue by NelsonAPenn** [NelsonAPenn/yact#21]
Many of the most popular languages are already supported by `yact` through external transformers-- one notable exception is C#.

> NOTE: `clang-format` technically has support for C#; however, it is unlikely that it is up to date with recent language features (it appears `clang-format` for Javascript has some issues as well).

Add support for formatting via `csharpier`. Should support

- System-wide installation:
    - Installed with `dotnet tool install -g csharpier`
    - Run with `csharpier` and options
- Project-local installation:
    - Installed with `dotnet tool install csharpier`
    - Run with `dotnet csharpier`and options.

See `prettier` configuration for a Node.js equivalent.

**Comment by NelsonAPenn** [comment]
I used a System transformer to run `csharpier` in a project (on macOS). Unfortunately it seemed like for the installation method at hand, it might have been implemented as a bash function rather than an executable, because "which csharpier" yielded no results.

The System transformer I used ended up using `bash -c "csharpier format"` as its command. Requires more thought 🤔 

For anyone with the same situation
```toml
[[items]]
glob = "**/*.cs"
transformers = [{ External = { System = { command = "bash", env = {}, args = ["-c", "csharpier format"]}}}]
```
